#
# Copyright (C) 2025 The Android Open Source Project
# Copyright (C) 2025 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/a35x

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

# APEX
DEXPREOPT_GENERATE_APEX_IMAGE := true

# Bootloader
BOARD_VENDOR := samsung
TARGET_SOC := s5e8835
TARGET_BOOTLOADER_BOARD_NAME := s5e8835
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_USES_UEFI := true
TARGET_BOARD_PLATFORM := erd8835
TARGET_CPU_SMP := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true
TARGET_USES_64_BIT_BINDER := true

# Display
TW_THEME := portrait_hdpi
TARGET_SCREEN_DENSITY := 390
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2340
TW_MAX_BRIGHTNESS := 1000
TW_DEFAULT_BRIGHTNESS := 500
TW_FRAMERATE := 120
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img

# Kernel
BOARD_BOOT_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive bootconfig buildtime_bootconfig=enable loop.max_part=7
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x00000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000000
BOARD_DTB_OFFSET := 0x00000000
BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION) --pagesize $(BOARD_KERNEL_PAGESIZE) --board "SRPWK02A003"
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB) --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/mkbootimg/mkbootimg.mk

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm system_ext vendor_dlkm
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 9122611200

# System as root
BOARD_ROOT_EXTRA_FOLDERS := carrier data_mirror debug_ramdisk efs linkerconfig metadata odm_dlkm oem optics postinstall prism second_stage_resources spu system_ext vendor_dlkm system_dlkm
BOARD_SUPPRESS_SECURE_ERASE := true

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TW_PREPARE_DATA_MEDIA_EARLY := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TW_INCLUDE_NTFS_3G := true
TARGET_USES_MKE2FS := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Verified Boot
BOARD_AVB_ENABLE := false

# Crypto
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
PLATFORM_VERSION := 14
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT := true
BOARD_USES_METADATA_PARTITION := true
TW_FORCE_KEYMASTER_VER := true

# TWRP flags
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true
TW_EXCLUDE_APEX := true
TW_NO_SCREEN_BLANK := true
RECOVERY_SDCARD_ON_DATA := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_NO_BIND_SYSTEM := true
TW_EXTRA_LANGUAGES := true
TW_ENABLE_FS_COMPRESSION := true
TW_NO_LEGACY_PROPS := true
TW_BACKUP_EXCLUSIONS := /data/fonts/files
TW_INCLUDE_FASTBOOTD := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_DEFAULT_USB_INIT := true

# Samsung
TW_NO_REBOOT_BOOTLOADER := true
TW_USE_SAMSUNG_HAPTICS := true
TW_HAS_DOWNLOAD_MODE := true
TW_USE_SERIALNO_PROPERTY_FOR_DEVICE_ID := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

# Status bar
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := "50"
TW_CUSTOM_CLOCK_POS := "300"
TW_CUSTOM_BATTERY_POS := "750"

# Logging
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TWRP_EVENT_LOGGING := true

# Props
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
PRODUCT_ENFORCE_VINTF_MANIFEST := true
TW_USE_LEGACY_BATTERY_SERVICES := true

# Version
TW_DEVICE_VERSION := ChristyGaming18
MAINTAINER := ChristyGaming18

# ============================================================
# RECOVERY SELECTOR
# export USE_RECOVERY=SHRP|TWRP|PBRP|OFRP antes de compilar
# ============================================================

ifeq ($(USE_RECOVERY),SHRP)
SHRP_DEVICE_CODE := a35x
SHRP_PATH := device/samsung/a35x
SHRP_MAINTAINER := ChristyGaming18
SHRP_REC_TYPE := Treble
SHRP_DEVICE_TYPE := A/B
SHRP_REC := "/dev/block/bootdevice/by-name/recovery"
SHRP_HAS_RECOVERY_PARTITION := true
SHRP_AB := true
SHRP_EDL_MODE := 1
SHRP_INTERNAL := "/sdcard"
SHRP_EXTERNAL := "/external_sd"
SHRP_OTG := "/usb_otg"
SHRP_FLASH := 1
SHRP_EXPRESS := true
SHRP_EXPRESS_USE_DATA := true
SHRP_CUSTOM_FLASHLIGHT := true
SHRP_FONP_1 := "/sys/devices/virtual/camera/flash/rear_flash"
SHRP_FLASH_MAX_BRIGHTNESS := 200
SHRP_STATUSBAR_RIGHT_PADDING := 58
SHRP_STATUSBAR_LEFT_PADDING := 58
SHRP_NOTCH := true
# Sin SHRP_DARK = tema claro
endif

ifeq ($(USE_RECOVERY),PBRP)
PB_TORCH_PATH := "/sys/devices/virtual/camera/flash/rear_flash"
PB_TORCH_MAX_BRIGHTNESS := 1
PB_MAINTAINER := ChristyGaming18
endif

ifeq ($(USE_RECOVERY),OFRP)
FOX_VERSION := R11.1
FOX_MAINTAINER := ChristyGaming18
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
FOX_AB_DEVICE := 1
FOX_RECOVERY_INSTALL_PARTITION := "/dev/block/bootdevice/by-name/recovery"
OF_MAINTAINER := ChristyGaming18
OF_SCREEN_H := 2340
OF_SCREEN_W := 1080
OF_STATUS_H := 0072
OF_STATUS_INDENT_LEFT := 58
OF_STATUS_INDENT_RIGHT := 58
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_FL_PATH1 := "/sys/devices/virtual/camera/flash/rear_flash"
OF_FLASHLIGHT_ENABLE := 1
endif
